### ISSUE TITLE
[ARM MAC M1 CHIP]ERROR: No matching distribution found for onnxruntime-gpu

### ISSUE THREAD

**Issue by weidutech** [s0md3v/roop#154]
**Describe the bug**
ERROR: No matching distribution found for onnxruntime-gpu

using arm mac m1 chip 

**To Reproduce**

pip3 install -r requirements.txt
or
pip3 install onnxruntime-gpu

**Details**
What OS are you using?
- [ ] Linux
- [ ] Linux in WSL
- [ ] Windows 
- [ yes] Mac

Are you try to use a GPU?
- [ ] No. I am not using the `---gpu` flag
- [ ] NVIDIA
- [ ] AMD
- [ ] Intel
- [ yes] Mac

**Sanity Check**
- [ ] I have the latest code from the github repository
- [yes ] I have followed the installation guide

**Comment by kelvinthh** [comment]
Just manually run 'pip install onnxruntime', follow the procedure in README.md. If you get any error saying some imports are missing on your first few run, just manually pip install them until it's gone. I alos use an M1 Mac, except GPU acceleration not working, it runs fine in CLI mode.

**Comment by weidutech** [comment]
without GPU acceleration, wouldn't it be very slow?

**Comment by kelvinthh** [comment]
On my maxed out M1 Pro MBP, a 15 sec 720p clip takes around 300 sec or more. The onnxruntime-silicon library mentioned in the README.md doesn't work after adding the --gpu argument, it would display error that says no CUDA found or something.

**Comment by s0md3v** [comment]
This issue should be fixed now. Clone the repo and try again.

@kelvinthh I'll fix that, brb.

**Comment by weidutech** [comment]
> Just manually run 'pip install onnxruntime', follow the procedure in README.md. If you get any error saying some imports are missing on your first few run, just manually pip install them until it's gone. I alos use an M1 Mac, except GPU acceleration not working, it runs fine in CLI mode.

**Comment by weidutech** [comment]
Did you faced this problem while pip install ? @kelvinthh 

insightface/thirdparty/face3d/mesh/cython/mesh_core_cython.cpp:784:10: fatal error: 'numpy/arrayobject.h' file not found
      #include "numpy/arrayobject.h"
               ^~~~~~~~~~~~~~~~~~~~~
      1 error generated.
      error: command '/usr/bin/clang' failed with exit code 1
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for insightface
Failed to build insightface
ERROR: Could not build wheels for insightface, which is required to install pyproject.toml-based projects

**Comment by s0md3v** [comment]
@kelvinthh the CUDA issue should be fixed now

**Comment by kelvinthh** [comment]
> Did you faced this problem while pip install ? @kelvinthh
> 
> insightface/thirdparty/face3d/mesh/cython/mesh_core_cython.cpp:784:10: fatal error: 'numpy/arrayobject.h' file not found #include "numpy/arrayobject.h" ^~~~~~~~~~~~~~~~~~~~~ 1 error generated. error: command '/usr/bin/clang' failed with exit code 1 [end of output]
> 
> note: This error originates from a subprocess, and is likely not a problem with pip. ERROR: Failed building wheel for insightface Failed to build insightface ERROR: Could not build wheels for insightface, which is required to install pyproject.toml-based projects

Unfortunately no. I start a new virtual env with conda and use Python 3.10.

**Comment by kelvinthh** [comment]
> @kelvinthh the CUDA issue should be fixed now

I did some testing afterwards, with fresh conda env each time, here's what I've found out:

> Scenario 1: Fresh virtual env, done pip install -r requirements.txt, with or without --gpu argument it will run without any issue, but it seems it's not using the Apple GPU anyway, I have the GPU usage window opened and witnessed no spike.
> 
> Scenario 2: After 'pip install -r requirements.txt', I uninstalled the normal onnxruntime and pip install onnxruntime-silicon, I would then get a CUDA not available error.
> Scenario 3: Almost the same with scenario 2 but did not uninstall onnxruntime instead. Still got the CUDA not available error.

so...unfortunately I think GPU acceleration is still not being utilized at the moment.

**Comment by giers10** [comment]
Implementing GPU support in onnxruntimes arm build (https://github.com/microsoft/onnxruntime) might solve this issue.

**Comment by melbouhy** [comment]
hello
when I try to install the silicon build I have an error
`pip install onnxruntime-silicon
ERROR: Could not find a version that satisfies the requirement onnxruntime-silicon (from versions: none)
ERROR: No matching distribution found for onnxruntime-silicon`

and tries to build (gpu accelerator) it as per the docs but I have an error
`python3.10/site-packages/torch/serialization.py", line 136, in validate_cuda_device
    raise RuntimeError('Attempting to deserialize object on a CUDA '
RuntimeError: Attempting to deserialize object on a CUDA device but torch.cuda.is_available() is False. If you are running on a CPU-only machine, please use torch.load with map_location=torch.device('cpu') to map your storages to the CPU.`

**Comment by kelvinthh** [comment]
> hello when I try to install the silicon build I have an error `pip install onnxruntime-silicon` ERROR: Could not find a version that satisfies the requirement onnxruntime-silicon (from versions: none) ERROR: No matching distribution found for onnxruntime-silicon
> 
> and tries to build (gpu accelerator) it as per the docs but I have an error `python3.10/site-packages/torch/serialization.py", line 136, in validate_cuda_device raise RuntimeError('Attempting to deserialize object on a CUDA ' RuntimeError: Attempting to deserialize object on a CUDA device but torch.cuda.is_available() is False. If you are running on a CPU-only machine, please use torch.load with map_location=torch.device('cpu') to map your storages to the CPU.`

`onnxruntime-silicon` requires Python 3.9/3.10, you're probably on 3.11 and it won't install if that's the case.

**Comment by melbouhy** [comment]
> > hello when I try to install the silicon build I have an error `pip install onnxruntime-silicon` ERROR: Could not find a version that satisfies the requirement onnxruntime-silicon (from versions: none) ERROR: No matching distribution found for onnxruntime-silicon
> > and tries to build (gpu accelerator) it as per the docs but I have an error `python3.10/site-packages/torch/serialization.py", line 136, in validate_cuda_device raise RuntimeError('Attempting to deserialize object on a CUDA ' RuntimeError: Attempting to deserialize object on a CUDA device but torch.cuda.is_available() is False. If you are running on a CPU-only machine, please use torch.load with map_location=torch.device('cpu') to map your storages to the CPU.`
> 
> `onnxruntime-silicon` requires Python 3.9/3.10, you're probably on 3.11 and it won't install if that's the case.

That indeed was correct and thanks for this!!! downgrading to pyton 3.10 did the trick and I could install it!!

**Comment by uPagge** [comment]
I don't really understand if it's possible to run it on Apple M1 Max. I tried the instruction with and without a GPU, in both cases there were errors during the build

**Comment by kelvinthh** [comment]
I got GPU acceleration on M1 Mac working [here](https://github.com/s0md3v/roop/issues/162#issuecomment-1571674371), Apple Silicon Mac cannot install `onnxruntime-gpu` but instead `onnxruntime-silicon` is needed. Also don't `pip install onnxruntime` for it supports only CPU for now, just install `onnxruntime-silicon` and you'll be fine. It wasn't working before because there is a if statement in `run.py` blocking non-CUDA GPU from using the `--gpu` argument, since Mac does not have CUDA and the script won't run further under this circumstance. Commenting out that if statement in `run.py` as I mentioned in the link should fix it for now.

However, a bug will also occur when utilizing GPU that your memory usage will skyrocket and even take up a huge chunk of your memory swap until the face swap is done, or your Mac decides that it's taking up too much resources and kills the process.

**Comment by uPagge** [comment]
> However, a bug will also occur when utilizing GPU that your memory usage will skyrocket and even take up a huge chunk of your memory swap until the face swap is done, or your Mac decides that it's taking up too much resources and kills the process.

Is it possible to somehow limit software consumption?

**Comment by uPagge** [comment]
The new version still saves an error with my M1 Max

Python run.py --gpu

You use the --gpu flag, but CUDA is not available or not properly installed on your system.

Also, ./build-macos.sh still returns an error, but the GPU can be installed manually

**Comment by jet3004** [comment]
Stoked to see so many people working to try to get this perfected on Mac, for once. Clearly still some loose ends but awesome to see, thanks all.

**Comment by kelvinthh** [comment]
> The new version still saves an error with my M1 Max
> 
> Python run.py --gpu
> 
> You use the --gpu flag, but CUDA is not available or not properly installed on your system.
> 
> Also, ./build-macos.sh still returns an error, but the GPU can be installed manually

As I mentioned earlier, after `pip install -r requirements.txt` get rid of `onnxruntime` with `pip uninstall onnxruntime`, than install `onnxruntime-silicon` with `pip install onnxruntime-silicon`, now you should be able to use `--gpu` on your M1/M1 Mac. You don't with to build `onnxruntime-silicon` on your own since it won't work anyway, just install `onnxruntime-silicon` on your own with `pip install`.  @s0md3v please update the wiki.

**Comment by kelvinthh** [comment]
> Which python version are you using? Installing onnxruntime-silicon on mac with both python 3.10 and 3.11 fails

check your Python version with `python --version` and see what version you're actually running, 3.11 won't do it but 3.10 should be fine. That's what I use in my conda env.

**Comment by Rigo-m** [comment]
> > Which python version are you using? Installing onnxruntime-silicon on mac with both python 3.10 and 3.11 fails
> 
> check your Python version with `python --version` & `pip --version` and see what version you're actually running, 3.11 won't do it but 3.10 should be fine. That's what I use in my conda env.

Actually my problem was being on big sur. You need macos > 12 for some deps (such as tensorflow) to work. Pip requirements are not very transparent

**Comment by weidutech** [comment]
> I got GPU acceleration on M1 Mac working [here](https://github.com/s0md3v/roop/issues/162#issuecomment-1571674371), Apple Silicon Mac cannot install `onnxruntime-gpu` but instead `onnxruntime-silicon` is needed. Also don't `pip install onnxruntime` for it supports only CPU for now, just install `onnxruntime-silicon` and you'll be fine. It wasn't working before because there is a if statement in `run.py` blocking non-CUDA GPU from using the `--gpu` argument, since Mac does not have CUDA and the script won't run further under this circumstance. Commenting out that if statement in `run.py` as I mentioned in the link should fix it for now.
> 
> However, a bug will also occur when utilizing GPU that your memory usage will skyrocket and even take up a huge chunk of your memory swap until the face swap is done, or your Mac decides that it's taking up too much resources and kills the process.

Yes indeed, this bug needs to be fixed, otherwise GPU acceleration is useless.
