### ISSUE TITLE
"You are using --gpu flag but CUDA isn't available on your system"

### ISSUE THREAD

**Issue by carlodrift** [s0md3v/roop#69]
Hey, I got this error, but I don't use this flag:
<img width="670" alt="image" src="https://github.com/s0md3v/roop/assets/30211659/65c3c4b5-520d-4b2f-a658-b6f323502335">

**Comment by yachty66** [comment]
same

**Comment by s0md3v** [comment]
This is fixed now.

@yachty66 @carlodrift

**Comment by Diletant-001** [comment]
@s0md3v not fixed for me unfortunately

![image](https://github.com/s0md3v/roop/assets/77320653/d5728e2a-747b-4d03-8be5-2274c1547559)
